networks:
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 40000000000
        cmd_settings:
            port: 8545
            gas_limit: 67219750
            accounts: 50
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@vittominacori=vittominacori/erc1363-payable-token@4.8.0'
